global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fd-api"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: /metrics

  - job_name: "fd-ingestor"
    static_configs:
      - targets: ["host.docker.internal:8081"]
    metrics_path: /metrics

  - job_name: "fd-worker"
    static_configs:
      - targets: ["host.docker.internal:8082"]
    metrics_path: /metrics

  - job_name: "nats"
    static_configs:
      - targets: ["nats:8222"]
    metrics_path: /metrics
